// src/components/HeroSection.vue
<template>
  <section
    id="hero"
    class="hero-section"
    aria-label="Introduction and hero section"
    :style="{ aspectRatio: '16/9' }"
  >
    <canvas
      ref="canvasRef"
      class="hero-canvas"
      aria-hidden="true"
      :style="{
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        zIndex: 1,
        opacity: isLoaded ? 1 : 0,
        transition: 'opacity 0.5s ease-in-out',
      }"
    />

    <div
      class="hero-fallback-bg"
      :style="{
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        background:
          'linear-gradient(135deg, #0a0a0a 0%, #1a0a2e 50%, #16213e 100%)',
        opacity: isLoaded ? 0 : 1,
        transition: 'opacity 0.5s ease-in-out',
        zIndex: 0,
      }"
    />

    <div class="hero-content" :style="{ zIndex: 2 }">
      <div class="hero-text">
        <h1 class="hero-greeting">Hi, I&apos;m</h1>
        <h2
          class="hero-name"
          aria-label="Steven Coaila Zaa, Full Stack Developer"
        >
          Steven Coaila Zaa
        </h2>
        <div
          class="hero-subtitle"
          role="text"
          aria-live="polite"
          aria-label="Dynamic title showing different specializations"
        >
          <Typewriter class="hero-title" />
        </div>
        <p
          class="hero-description"
          aria-label="Professional summary and approach"
        >
          Creating innovative digital experiences with modern web technologies.
          Passionate about clean code, beautiful design, and exceptional user
          experiences.
        </p>
        <div class="hero-cta-container">
          <button
            class="hero-cta hero-cta-primary"
            aria-label="View my projects"
            type="button"
            @click="scrollToProjects"
          >
            <span>View Projects</span>
            <ArrowRight class="cta-icon" :size="20" :stroke-width="2" />
          </button>

          <a
            href="mailto:scoaila@proton.me"
            class="hero-cta hero-cta-secondary"
            aria-label="Send me an email"
          >
            <span>Contact Me</span>
            <Mail class="cta-icon" :size="20" :stroke-width="2" />
          </a>
        </div>
      </div>
    </div>

    <ErrorBoundary v-if="show3D">
      <Suspense>
        <template #default>
          <ThreeScene :canvas="canvasRef" @loaded="isLoaded = true" />
        </template>
        <template #fallback></template>
      </Suspense>
    </ErrorBoundary>
  </section>
</template>

<script setup>
import { defineAsyncComponent, onMounted, onUnmounted, ref } from "vue";
import { ArrowRight, Mail } from "lucide-vue-next";
import { runIdle } from "../utils/idle";
import ErrorBoundary from "./ErrorBoundary.vue";
import Typewriter from "./Typewriter.vue";
import "../styles/HeroSection.css";

const ThreeScene = defineAsyncComponent(() => import("./ThreeScene.vue"));

const canvasRef = ref(null);
const isLoaded = ref(false);
const show3D = ref(false);

let cancelIdle = null;

function scrollToProjects() {
  const projectsSection = document.getElementById("projects");
  const prefersReducedMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;
  projectsSection?.scrollIntoView({
    behavior: prefersReducedMotion ? "auto" : "smooth",
  });
}

onMounted(() => {
  const prefersReducedMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;
  if (prefersReducedMotion) return;

  cancelIdle = runIdle(() => {
    show3D.value = true;
  }, { timeout: 1500 });
});

onUnmounted(() => {
  cancelIdle?.();
});
</script>

// src/components/HeroSection.jsx
import React, { useRef, useEffect, useState, lazy, Suspense } from 'react';

// Lazy load Three.js components only when needed
const ThreeScene = lazy(() => 
  import('./ThreeScene').then(module => ({ default: module.ThreeScene }))
);

const HeroSection = () => {
  const canvasRef = useRef(null);
  const [isLoaded, setIsLoaded] = useState(false);
  const [show3D, setShow3D] = useState(false);

  // Progressive enhancement: Load 3D effects after page is interactive
  useEffect(() => {
    // Delay 3D loading until after content is rendered and page is interactive
    const timer = setTimeout(() => {
      // Check if user prefers reduced motion
      const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      
      // Only load 3D if user doesn't prefer reduced motion and device can handle it
      if (!prefersReducedMotion) {
        setShow3D(true);
      }
    }, 500); // Reduced delay for faster 3D loading

    return () => {
      clearTimeout(timer);
    };
  }, []);

  const handleThreeLoaded = () => {
    setIsLoaded(true);
  };

  return (
    <section className="hero-section" style={{ aspectRatio: '16/9' }}>
      {/* Canvas with reserved space to prevent CLS */}
      <canvas 
        ref={canvasRef} 
        className="hero-canvas"
        style={{ 
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          zIndex: 1,
          opacity: isLoaded ? 1 : 0,
          transition: 'opacity 0.5s ease-in-out'
        }}
        aria-hidden="true"
      />

      {/* Fallback gradient background for when 3D is loading/disabled */}
      <div 
        className="hero-fallback-bg"
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          background: 'linear-gradient(135deg, #0a0a0a 0%, #1a0a2e 50%, #16213e 100%)',
          opacity: isLoaded ? 0 : 1,
          transition: 'opacity 0.5s ease-in-out',
          zIndex: 0
        }}
      />

      {/* Hero Content - Loads immediately for fast FCP */}
      <div className="hero-content" style={{ zIndex: 2 }}>
        <div className="hero-text">
          <h1 className="hero-greeting">Hi, I&apos;m</h1>
          <h2 className="hero-name">Steven Coaila Zaa</h2>
          <div className="hero-subtitle">
            <span className="hero-title">Full Stack Developer</span>
          </div>
          <p className="hero-description">
            Creating innovative digital experiences with modern web technologies.
            Passionate about clean code, beautiful design, and exceptional user experiences.
          </p>
        </div>
      </div>

      {/* Lazy load Three.js scene only when needed */}
      {show3D && (
        <Suspense fallback={null}>
          <ThreeScene 
            canvasRef={canvasRef}
            onLoaded={handleThreeLoaded}
          />
        </Suspense>
      )}
    </section>
  );
};

export default HeroSection;
