// src/components/ProjectsSection.vue
<template>
  <div ref="sectionRef" class="projects-section">
    <div v-if="!projects.length" class="projects-empty">
      <p>No projects to display</p>
    </div>

    <template v-else>
      <div class="projects-header">
        <h2 class="section-title">Featured Projects</h2>
        <p class="section-subtitle">Here are some of my recent works</p>
      </div>

      <div class="projects-grid">
        <ProjectCard
          v-for="(project, index) in projects"
          :key="project.id"
          :project="project"
          :index="index"
        />
      </div>
    </template>
  </div>
</template>

<script setup>
import { onMounted, onUnmounted, ref } from "vue";
import { gsap, ScrollTrigger } from "../lib/gsap";
import ProjectCard from "./ProjectCard.vue";
import "../styles/ProjectsSection.css";

const props = defineProps({
  projects: { type: Array, default: () => [] },
});

const sectionRef = ref(null);
let trigger = null;

function animateTitlePhase(header, section, phaseLocalProgress, totalProjects) {
  const navbarHeight =
    parseInt(
      getComputedStyle(document.documentElement).getPropertyValue(
        "--navbar-height"
      )
    ) || 80;
  const buffer = 150;
  const titleMaxDistance = window.innerHeight / 2 + navbarHeight + buffer;
  const opacity = Math.max(0, 1 - phaseLocalProgress * 1.8);

  gsap.to(header, {
    opacity,
    y: -titleMaxDistance * phaseLocalProgress,
    duration: 0.2,
    ease: "power2.out",
  });

  header.classList.toggle("hidden", opacity < 0.1);

  for (let index = 0; index < totalProjects; index++) {
    const card = section.querySelector(`[data-project="${index}"]`);
    if (!card) continue;
    const currentY = gsap.getProperty(card, "y");
    gsap.to(card, {
      opacity: 0,
      y: currentY,
      duration: 0.25,
      ease: "power2.out",
      overwrite: "auto",
      immediateRender: false,
    });
    card.classList.add("hidden");
  }
}

function animateCurrentProject(card, index, totalProjects, phaseLocalProgress) {
  const isLastProject = index === totalProjects - 1;

  if (isLastProject) {
    const easedProgress =
      phaseLocalProgress <= 0.5
        ? gsap.utils.mapRange(0, 0.5, 0, 1, phaseLocalProgress)
        : 1;

    gsap.to(card, {
      opacity: easedProgress,
      y: 0,
      duration: 0.3,
      ease: "power3.out",
    });

    card.classList.toggle("hidden", easedProgress <= 0.1);
    return;
  }

  let easedOpacity = 1;
  let yPosition = 0;

  if (phaseLocalProgress <= 0.3) {
    easedOpacity = gsap.utils.mapRange(0, 0.3, 0, 1, phaseLocalProgress);
    yPosition = 0;
  } else if (phaseLocalProgress <= 0.7) {
    easedOpacity = 1;
    yPosition = 0;
  } else {
    const exitProgress = gsap.utils.mapRange(0.8, 1, 0, 1, phaseLocalProgress);
    easedOpacity = Math.max(0, 1 - exitProgress);

    const navbarHeight =
      parseInt(
        getComputedStyle(document.documentElement).getPropertyValue(
          "--navbar-height"
        )
      ) || 80;
    const buffer = 20;
    const maxDistance = window.innerHeight / 2 + navbarHeight + buffer;
    yPosition = -maxDistance * exitProgress;
  }

  gsap.to(card, {
    opacity: easedOpacity,
    y: yPosition,
    duration: 0.25,
    ease: "power2.out",
    overwrite: "auto",
    immediateRender: false,
  });

  card.classList.toggle("hidden", easedOpacity <= 0.05);
}

function animateProjectPhases(
  header,
  section,
  currentPhase,
  phaseLocalProgress,
  totalProjects
) {
  gsap.to(header, {
    opacity: 0,
    y: -30,
    duration: 0.25,
    ease: "power2.out",
    overwrite: "auto",
    immediateRender: false,
  });
  header.classList.add("hidden");

  const projectIndex = currentPhase - 1;

  for (let index = 0; index < totalProjects; index++) {
    const card = section.querySelector(`[data-project="${index}"]`);
    if (!card) continue;

    if (index === projectIndex) {
      animateCurrentProject(card, index, totalProjects, phaseLocalProgress);
      continue;
    }

    const currentY = gsap.getProperty(card, "y");
    gsap.to(card, {
      opacity: 0,
      y: currentY,
      duration: 0.25,
      ease: "power2.out",
      overwrite: "auto",
      immediateRender: false,
    });
    card.classList.add("hidden");
  }
}

onMounted(() => {
  if (!props.projects.length) return;
  const section = sectionRef.value;
  if (!section) return;

  const header = section.querySelector(".projects-header");
  if (!header) return;

  gsap.set(header, { opacity: 1, y: 0 });

  props.projects.forEach((_, index) => {
    const card = section.querySelector(`[data-project="${index}"]`);
    if (!card) return;
    gsap.set(card, { opacity: 0, y: 0 });
    card.classList.add("hidden");
  });

  const totalPhases = 1 + props.projects.length;

  trigger = ScrollTrigger.create({
    trigger: section,
    start: "top+=6rem top",
    end: () => `+=${totalPhases * 1.8 * window.innerHeight}`,
    pin: true,
    pinSpacing: true,
    scrub: 1,
    anticipatePin: 1,
    refreshPriority: -1,
    fastScrollEnd: true,
    invalidateOnRefresh: true,
    onUpdate: (self) => {
      const progress = self.progress;
      const phaseProgress = progress * totalPhases;
      const currentPhase = Math.floor(phaseProgress);
      let phaseLocalProgress = phaseProgress - currentPhase;

      if (phaseLocalProgress > 0.2 && phaseLocalProgress < 0.8) {
        const normalizedMiddle = (phaseLocalProgress - 0.2) / 0.6;
        const slowProgress = normalizedMiddle * 0.3;
        phaseLocalProgress = 0.2 + slowProgress;
      }

      if (currentPhase === 0) {
        animateTitlePhase(
          header,
          section,
          phaseLocalProgress,
          props.projects.length
        );
      } else if (currentPhase >= 1 && currentPhase <= props.projects.length) {
        animateProjectPhases(
          header,
          section,
          currentPhase,
          phaseLocalProgress,
          props.projects.length
        );
      }
    },
  });
});

onUnmounted(() => {
  trigger?.kill();
  trigger = null;
});
</script>

// src/components/ProjectsSection.jsx
import React, { useRef, useEffect } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import '../styles/ProjectsSection.css';

// Register GSAP plugin
gsap.registerPlugin(ScrollTrigger);

const ProjectCard = ({ project, index }) => {
  const isEven = index % 2 === 0;

  return (
    <div
      className={`project-card ${isEven ? 'image-right' : 'image-left'}`}
      data-project={index}
    >
      <div className="project-content">
        <div className="project-info">
          <div className="project-number">
            {String(index + 1).padStart(2, '0')}
          </div>
          <h3 className="project-title">{project.title}</h3>
          <p className="project-description">{project.description}</p>

          <div className="project-tech">
            {project.tech.map((tech, techIndex) => (
              <span key={techIndex} className="tech-tag">
                {tech}
              </span>
            ))}
          </div>

          {project.features && (
            <div className="project-features">
              <h4 className="features-title">Key Features:</h4>
              <ul className="features-list">
                {project.features.slice(0, 3).map((feature, featureIndex) => (
                  <li key={featureIndex} className="feature-item">
                    {feature}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="project-links">
            {project.github && project.github !== '#' && (
              <a
                href={project.github}
                target="_blank"
                rel="noopener noreferrer"
                className="project-link"
              >
                GitHub
              </a>
            )}
            {project.demo && project.demo !== '#' && (
              <a
                href={project.demo}
                target="_blank"
                rel="noopener noreferrer"
                className="project-link"
              >
                Demo
              </a>
            )}
          </div>
        </div>

        <div className="project-visual">
          <div className="project-showcase">
            <div className="project-image">
              {project.image ? (
                <img src={project.image} alt={project.title} />
              ) : (
                <div className="project-placeholder">
                  <span>{project.title}</span>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const ProjectsSection = ({ projects = [] }) => {
  const sectionRef = useRef(null);

  useEffect(() => {
    if (!projects.length) return;

    const section = sectionRef.current;
    if (!section) return;

    const header = section.querySelector('.projects-header');

    // Set initial states
    gsap.set(header, { opacity: 1, y: 0 });

    projects.forEach((_, index) => {
      const card = section.querySelector(`[data-project="${index}"]`);
      if (!card) return;
      gsap.set(card, { opacity: 0, y: 0 }); // Start at center, not at 50px below position
    });

    // Main pinned section
    const totalPhases = 1 + projects.length;
    const totalHeight = (totalPhases - 0.5) * window.innerHeight; // Reducir ligeramente para mejor control

    ScrollTrigger.create({
      trigger: section,
      start: 'top top', // Inicio directo sin gap
      end: `+=${totalHeight}`,
      pin: true,
      pinSpacing: true, // Restaurar el pin spacing para que funcione el scroll fijo
      scrub: 1,
      anticipatePin: 1,
      refreshPriority: -1,
      onUpdate: (self) => {
        const progress = self.progress;
        const phaseProgress = progress * totalPhases;
        const currentPhase = Math.floor(phaseProgress);
        const phaseLocalProgress = phaseProgress - currentPhase;

        // Phase 0: Title visible immediately, then fades upward
        if (currentPhase === 0) {
          // Calculate dynamic distance for title (slightly more dramatic)
          const navbarHeight = 80;
          const buffer = 150; // Larger buffer for title, more dramatic
          const titleMaxDistance =
            window.innerHeight / 2 + navbarHeight + buffer;

          gsap.to(header, {
            opacity: Math.max(0, 1 - phaseLocalProgress * 1.8), // Faster fade
            y: -titleMaxDistance * phaseLocalProgress, // Dynamic upward movement
            duration: 0.2, // Faster animation
            ease: 'power2.out', // Cambio a power2.out para mejor efecto de salida
          });

          // Hide projects - maintain current position
          projects.forEach((_, index) => {
            const card = section.querySelector(`[data-project="${index}"]`);
            if (card) {
              const currentY = gsap.getProperty(card, 'y');
              gsap.to(card, {
                opacity: 0,
                y: currentY, // Maintain current position, don't reset
                duration: 0.4,
                ease: 'power2.inOut',
                overwrite: true, // Prevenir conflictos
              });
            }
          });
        }

        // Project phases
        else if (currentPhase >= 1 && currentPhase <= projects.length) {
          // Title completely hidden
          gsap.to(header, {
            opacity: 0,
            y: -30,
            duration: 0.4,
            ease: 'power2.inOut',
          });

          const projectIndex = currentPhase - 1;

          projects.forEach((_, index) => {
            const card = section.querySelector(`[data-project="${index}"]`);
            if (!card) return;

            if (index === projectIndex) {
              if (index === projects.length - 1) {
                // Último proyecto: aparece y se mantiene
                const easedProgress = gsap.utils.mapRange(
                  0,
                  1,
                  0,
                  1,
                  phaseLocalProgress
                );
                gsap.to(card, {
                  opacity: easedProgress,
                  y: 0, // Último proyecto se mantiene en centro
                  duration: 0.5,
                  ease: 'power3.out',
                });
              } else {
                // Previous projects: appear in center and disappear upward
                const easedOpacity = Math.sin(phaseLocalProgress * Math.PI);

                // Calculate dynamic distance based on viewport
                const navbarHeight = 80; // Altura del navbar
                const buffer = 20; // Buffer to ensure disappearance before navbar
                const maxDistance =
                  window.innerHeight / 2 + navbarHeight + buffer;

                const yPosition =
                  phaseLocalProgress <= 0.5
                    ? 0 // Primera mitad: mantener en centro mientras aparece
                    : -maxDistance * ((phaseLocalProgress - 0.5) * 2); // Second half: move upward dynamically

                gsap.to(card, {
                  opacity: easedOpacity,
                  y: yPosition,
                  duration: 0.4,
                  ease: 'power3.out',
                  overwrite: true, // Prevenir conflictos de animaciones

                });
              }
            } else {
              // Other hidden projects - maintain current position, don't reset
              const currentY = gsap.getProperty(card, 'y');
              gsap.to(card, {
                opacity: 0,
                y: currentY, // Maintain current Y position, don't move to another position
                duration: 0.4,
                ease: 'power2.inOut',
                overwrite: true, // Prevenir conflictos
              });
            }
          });
        }
      },
    });

    return () => {
      ScrollTrigger.getAll().forEach((st) => {
        if (st.trigger && section.contains(st.trigger)) {
          st.kill();
        }
      });
    };
  }, [projects]);

  if (!projects.length) {
    return (
      <div className="projects-empty">
        <p>No projects to display</p>
      </div>
    );
  }

  return (
    <div ref={sectionRef} className="projects-section">
      <div className="projects-header">
        <h2 className="section-title">Featured Projects</h2>
        <p className="section-subtitle">Here are some of my recent works</p>
      </div>

      <div className="projects-grid">
        {projects.map((project, index) => (
          <ProjectCard key={project.id} project={project} index={index} />
        ))}
      </div>
    </div>
  );
};

export default ProjectsSection;
