// src/components/SkillChip.vue
<template>
  <div class="skill-chip" :style="{ '--skill-color': skill.color }">
    <div class="skill-chip-icon">
      <TechIcon :name="skill.icon" />
    </div>
    <span class="skill-chip-name">{{ skill.name }}</span>
  </div>
</template>

<script setup>
import TechIcon from "./icons/TechIcon.vue";

defineProps({
  skill: { type: Object, required: true },
});
</script>

// src/components/SkillChip.jsx
import { TechIcons } from "./icons/TechIcons";

const SkillChip = ({ skill }) => {
  return (
    <div
      className="skill-chip"
      style={{
        "--skill-color": skill.color,
      }}
    >
      <div className="skill-chip-icon">{TechIcons[skill.icon]}</div>
      <span className="skill-chip-name">{skill.name}</span>
    </div>
  );
};

export default SkillChip;
