// src/components/SkillsSection.jsx
import { useRef, useState, useEffect } from "react";
import { gsap } from "gsap";
import { useGSAP } from "@gsap/react";
import { skillsData, skillCategories } from "../data/skills";
import SkillChip from "./SkillChip";
import "../styles/SkillsSection.css";

const SkillsSection = ({ skillsRef }) => {
  const sectionRef = useRef(null);
  const chipsContainerRef = useRef(null);
  const [activeCategory, setActiveCategory] = useState("all");
  const [hasAnimatedHeader, setHasAnimatedHeader] = useState(false);

  const filteredSkills =
    activeCategory === "all"
      ? skillsData
      : skillsData.filter((skill) => skill.category === activeCategory);

  // Header animation - only once on scroll
  useGSAP(
    () => {
      if (hasAnimatedHeader) return;

      const section = sectionRef.current;
      const header = section.querySelector(".skills-header");
      const filters = section.querySelector(".skills-filter");

      gsap.fromTo(
        [header, filters],
        { y: 40, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 0.8,
          ease: "power3.out",
          stagger: 0.15,
          scrollTrigger: {
            trigger: section,
            start: "top 80%",
            once: true,
            onEnter: () => setHasAnimatedHeader(true),
          },
        }
      );
    },
    { scope: sectionRef }
  );

  // Chips animation - on category change
  useEffect(() => {
    const container = chipsContainerRef.current;
    if (!container) return;

    const chips = container.querySelectorAll(".skill-chip");

    gsap.fromTo(
      chips,
      { scale: 0.8, opacity: 0 },
      {
        scale: 1,
        opacity: 1,
        duration: 0.4,
        ease: "back.out(1.7)",
        stagger: 0.03,
      }
    );
  }, [activeCategory]);

  return (
    <div ref={sectionRef} className="skills-section">
      <div ref={skillsRef} className="skills-anchor" />
      <div className="skills-header">
        <h2 className="section-title">Tech Stack</h2>
        <p className="section-subtitle">
          Technologies I use to bring ideas to life
        </p>
      </div>

      {/* Category Filter */}
      <div className="skills-filter">
        {skillCategories.map((cat) => (
          <button
            key={cat.id}
            className={`filter-btn ${
              activeCategory === cat.id ? "active" : ""
            }`}
            onClick={() => setActiveCategory(cat.id)}
            type="button"
          >
            {cat.label}
          </button>
        ))}
      </div>

      {/* Skills Grid */}
      <div ref={chipsContainerRef} className="skills-chips-grid">
        {filteredSkills.map((skill) => (
          <SkillChip key={skill.name} skill={skill} />
        ))}
      </div>
    </div>
  );
};

export default SkillsSection;

// src/components/SkillsSection.vue
<template>
  <div ref="sectionRef" class="skills-section">
    <div id="skills" class="skills-anchor" />

    <div class="skills-header">
      <h2 class="section-title">Tech Stack</h2>
      <p class="section-subtitle">Technologies I use to bring ideas to life</p>
    </div>

    <div class="skills-filter">
      <button
        v-for="cat in skillCategories"
        :key="cat.id"
        class="filter-btn"
        :class="{ active: activeCategory === cat.id }"
        type="button"
        @click="activeCategory = cat.id"
      >
        {{ cat.label }}
      </button>
    </div>

    <div ref="chipsContainerRef" class="skills-chips-grid">
      <SkillChip
        v-for="skill in filteredSkills"
        :key="skill.name"
        :skill="skill"
      />
    </div>
  </div>
</template>

<script setup>
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";
import { gsap } from "../lib/gsap";
import { skillsData, skillCategories } from "../data/skills";
import SkillChip from "./SkillChip.vue";
import "../styles/SkillsSection.css";

const sectionRef = ref(null);
const chipsContainerRef = ref(null);
const activeCategory = ref("all");

const filteredSkills = computed(() => {
  if (activeCategory.value === "all") return skillsData;
  return skillsData.filter((skill) => skill.category === activeCategory.value);
});

let headerTrigger = null;

function animateChips() {
  const container = chipsContainerRef.value;
  if (!container) return;

  const chips = container.querySelectorAll(".skill-chip");
  gsap.fromTo(
    chips,
    { scale: 0.8, opacity: 0 },
    {
      scale: 1,
      opacity: 1,
      duration: 0.4,
      ease: "back.out(1.7)",
      stagger: 0.03,
      overwrite: "auto",
    }
  );
}

onMounted(() => {
  const reducedMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;
  if (reducedMotion || !sectionRef.value) return;

  const header = sectionRef.value.querySelector(".skills-header");
  const filters = sectionRef.value.querySelector(".skills-filter");

  headerTrigger = gsap.fromTo(
    [header, filters],
    { y: 40, opacity: 0 },
    {
      y: 0,
      opacity: 1,
      duration: 0.8,
      ease: "power3.out",
      stagger: 0.15,
      scrollTrigger: {
        trigger: sectionRef.value,
        start: "top 80%",
        once: true,
      },
    }
  );

  animateChips();
});

watch(activeCategory, async () => {
  await nextTick();
  animateChips();
});

onUnmounted(() => {
  headerTrigger?.scrollTrigger?.kill();
  headerTrigger?.kill?.();
});
</script>
